### PR TITLE
Apiv3

### PR DESCRIPTION
**Pull request by kusold**
Addresses #40 #41 #42 

This is lightly tested considering the amount of changes that happened. Todoist API version 5 -> 7. HabitRPG API version 2 -> 3.

### CODE REVIEW

**Comment by eringiglio** [comment]
Not currently working for me, unfortunately!

**Comment by kusold** [comment]
@eringiglio Please open an issue and include what version you are running ( `npm list -g todoist-habitrpg`) and the output when you run it.

**Comment by eringiglio** [comment]
Fixed it--had tried to update via github, had forgotten that that doesn't work. My bad, not yours, and it's working now!

**Comment by kusold** [comment]
@eringiglio Perfect. Please let me know if you find any issues. This required bumping API version for both habitrpg and todoist, so I might have missed something new.

**Pull request merged**
